- hosts: all

  sudo: yes
  
  pre_tasks:
    - name: make sure that vagrant has the right permissions
      lineinfile: 'dest=/etc/sudoers regexp="vagrant ALL=(ALL) NOPASSWD: ALL" line="vagrant ALL=(ALL) NOPASSWD: ALL"'

    - name: install git
      apt: name=git state=present

  roles:
    - influxdb-092

    - uwsgi-emperor

    - role: uwsgi-python-app
      app_name: influxer
      python_packages:
        - "git+https://github.com/theonion/influxer2/influxer2#egg=influxer2"
      uwsgi:
        - module: "influxer2.wsgi:application"
          http: "{{ ansible_eth0.ipv4.address }}:80"
          master: yes
          gevent: 100
      app_enabled: yes

  post_tasks:
    - name: install libcap to enable uwsgi to bind to port 80
      apt: name=libcap2-bin state=present

    - name: bind uwsgi to port 80
      command: setcap 'cap_net_bind_service=+ep' /usr/local/bin/uwsgi
